sonar.projectKey=fullstack-project
sonar.projectName=fullstack-project

sonar.sources=backend,frontend/src

sonar.sourceEncoding=UTF-8

sonar.exclusions=backend/venv/**,backend/**/__pycache__/**,backend/**/*.pyc,frontend/node_modules/**,frontend/dist/**
